export const WORKOUT = [{
    "arms": [
      "Push-Ups",
      "Pull-Ups",
      "Dips",
      "Bicep Curls",
      "Tricep Dips",
      "Hammer Curls",
      "Skull Crushers",
      "Chin-Ups",
      "Diamond Push-Ups",
      "Close-Grip Bench Press",
      "Preacher Curls",
      "French Press",
      "Incline Dumbbell Curls",
      "Tricep Kickbacks",
      "Concentration Curls",
      "Lying Tricep Extensions",
      "Barbell Curl",
      "Overhead Tricep Extension",
      "Reverse Curl",
      "Tricep Rope Pushdown"
    ],
    "legs": [
      "Squats",
      "Lunges",
      "Deadlifts",
      "Leg Press",
      "Calf Raises",
      "Romanian Deadlifts",
      "Step-Ups",
      "Bulgarian Split Squats",
      "Box Jumps",
      "Hack Squats",
      "Sumo Deadlifts",
      "Front Squats",
      "Seated Leg Curls",
      "Single-Leg Deadlifts",
      "Leg Extensions",
      "Good Mornings",
      "Hip Thrusts",
      "Side Lunges",
      "Wall Sits",
      "Glute Bridges"
    ],
    "back": [
      "Pull-Ups",
      "Deadlifts",
      "Bent-Over Rows",
      "Lat Pulldowns",
      "T-Bar Rows",
      "Seated Cable Rows",
      "Chin-Ups",
      "Face Pulls",
      "Single-Arm Dumbbell Rows",
      "Barbell Shrugs",
      "Pendlay Rows",
      "Wide-Grip Pulldowns",
      "One-Arm Lat Pulldowns",
      "Close-Grip Pull-Downs",
      "Inverted Rows",
      "Bent-Over Rear Delt Raises",
      "Meadows Rows",
      "Kroc Rows",
      "Hyperextensions",
      "Renegade Rows"
    ],
    "shoulders": [
      "Overhead Press",
      "Lateral Raises",
      "Front Raises",
      "Rear Delt Flyes",
      "Arnold Press",
      "Upright Rows",
      "Face Pulls",
      "Shrugs",
      "Handstand Push-Ups",
      "Push Press",
      "Lateral Raises",
      "Cable Front Raises",
      "Cuban Press",
      "Seated Shoulder Press",
      "Bent-Over Dumbbell Lateral Raises",
      "Standing Military Press",
      "Lateral Raise Machine",
      "Seated Dumbbell Press",
      "Behind-the-Neck Press",
      "High Pulls"
    ],
    "abs": [
      "Planks",
      "Crunches",
      "Leg Raises",
      "Russian Twists",
      "Bicycle Crunches",
      "Hanging Leg Raises",
      "Mountain Climbers",
      "Woodchoppers",
      "Ab Wheel Rollouts",
      "Side Planks",
      "V-Ups",
      "Reverse Crunches",
      "Jackknife Sit-Ups",
      "Lying Leg Raises",
      "Cable Crunches",
      "Decline Crunches",
      "Flutter Kicks",
      "Seated Russian Twists",
      "Medicine Ball Slams",
      "Hollow Body Hold"
    ]
  }
  ];
export const WORKOUT_TYPES =[
      "Strength Training",
      "Cardiovascular Training",
      "High-Intensity Interval Training (HIIT)",
      "CrossFit",
      "Yoga",
      "Pilates",
      "Bodyweight Training",
      "Circuit Training",
      "Functional Training",
      "Powerlifting",
      "Weightlifting",
      "Calisthenics",
      "Running",
      "Cycling",
      "Swimming",
      "Boxing",
      "Kickboxing",
      "Muay Thai",
      "Martial Arts",
      "Zumba",
      "Dance Fitness",
      "Plyometrics",
      "TRX Training",
      "Tabata",
      "Barre",
      "Aerobics",
      "Step Aerobics",
      "Piloxing",
      "Spinning",
      "Rowing",
      "Body Combat",
      "Bootcamp",
      "Circuit Training",
      "Functional Training",
      "Parkour",
      "Hiking",
      "Rock Climbing",
      "Sprint Training",
      "Circuit Boxing",
      "Paddleboarding",
      "Crosstrainer Workouts",
      "Swiss Ball Workouts",
      "Stair Climbing",
      "Kettlebell Workouts",
      "Rowing Machine Workouts",
      "Suspension Trainer Workouts",
      "Battle Rope Workouts",
      "Interval Running",
      "Stretching & Flexibility Work",
      "Outdoor Calisthenics",
      "Bodybuilding",
      "Strongman Training",
      "Kettlebell Sport",
      "Rowing",
      "Pole Fitness",
      "Climbing Stairs",
      "Plyo Box Workouts",
      "F45 Training",
      "Kickboxing",
      "Functional Bodybuilding",
      "Animal Flow",
      "HIIT Yoga",
      "Judo",
      "Tai Chi",
      "Synchronized Swimming",
      "Power Yoga",
      "Gymnastics",
      "Kettlebell Yoga Fusion",
      "Surfing",
      "Ballet",
      "Hula Hooping Workouts",
      "Bikram Yoga",
      "Tabata Kickboxing",
      "BollyX",
      "Indoor Cycling",
      "Krav Maga",
      "Aerial Yoga",
      "Capoeira",
      "Paddleboard Yoga",
      "Barre Fitness",
      "Indoor Rowing",
      "AcroYoga",
      "Circuit Pilates",
      "Bounce Fit",
      "Zumba Toning",
      "Aqua Aerobics",
      "Kangoo Jumps",
      "Kickbox Fusion",
      "Prenatal Yoga",
      "Kundalini Yoga",
      "Jazzercise",
      "Qigong",
      "Reformer Pilates",
      "Powerlifting",
      "Marathon Training",
      "Mixed Martial Arts (MMA) Training",
      "Tae Bo",
      "Les Mills BodyPump",
      "HITTWORX",
      "Aqua Zumba",
      "MMA Conditioning",
      "Cardio Kickboxing",
      "Prancercise",
      "Spartan Race Training",
      "Aerial Silks",
      "Bollywood Dance Workouts",
      "Insanity Workout",
      "Hiking",
      "Snowboarding",
      "Zuu Workouts"
];